### ISSUE TITLE
Fix actor types inconsistency

### ISSUE THREAD

**Issue by albertxos** [crossbario/xbr-protocol#89]
should be:

`const ActorType_PROVIDER = 3;`

https://github.com/crossbario/xbr-protocol/blob/c416ae5cd7d828232c8cf19d5506cd1862bf8ea0/test/03_market.js#L128

**Comment by oberstet** [comment]
there definitely seems to be some inconsistency between

* https://github.com/crossbario/xbr-protocol/blob/master/contracts/XBRTypes.sol#L36

and what the xbr client libraries expose, as in, eg

* https://github.com/crossbario/cfxdb/blob/master/cfxdb/xbr.fbs#L123
* https://github.com/crossbario/autobahn-python/blob/master/autobahn/xbr/__init__.py#L147

my guess is, that the additional values in the latter ^ vs solidity came later, we didn't manage to sync both again until today, but that also means, that the actual market maker code likely uses hard-coded actor types, rather above (wrong, because out of sync) constants;) reopening for later detailed inspection and fix.

**Comment by oberstet** [comment]
fixed on master - the correct actor types are https://github.com/crossbario/xbr-protocol/blob/f2811532894e9a34228228e280cd67fc5b1fc6c6/contracts/XBRTypes.sol#L33

> note: there is 1 new value `PROVIDER_CONSUMER == 3`, which allows joining a market as both a consumer-actor and a provider-actor in one transaction

**Comment by oberstet** [comment]
the corresponding python enum does have the old 1/2 values, but not yet the new value 3 : https://github.com/crossbario/cfxdb/issues/16
