### ISSUE TITLE
XBRMarketMaker.onUserError(): "MismatchedABI" on CrossbarFX

### ISSUE THREAD

**Issue by boinalibo** [crossbario/xbr-protocol#97]
Hi,

We are facing an issue when we deploy CrossbarFX 20.3.1 edge node. We have deployed all XBR smart contracts on a Ganache but we still have an error message when CrossbarFX starts: **XBRMarketMaker.onUserError(): "MismatchedABI: ("The function 'marketsByMaker' was not found in this contract's abi).**

We are using these following components versions:
CrossbarFX: crossbarfx-linux-amd64-20200304-886d0bb (20.3.1)
Ganache CLI: 6.9.1
XBR protocol: 20.3.1

We don't know what wrong. Please, can you help us ?

Here is the full error stack trace:

**XBRMarketMaker.onUserError(): "MismatchedABI: ("The function 'marketsByMaker' was not found in this contract's abi. ", 'Are you sure you provided the correct contract abi?')"**
Traceback (most recent call last):
  File ".tox/buildexe/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
  File "crossbarfx/edge/worker/xbrmm.py", line 109, in start_maker
  File ".tox/buildexe/lib/python3.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
  File ".tox/buildexe/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
--- <exception caught here> ---
  File "crossbarfx/edge/worker/xbrmm.py", line 109, in start_maker
  File ".tox/buildexe/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
  File "crossbarfx/edge/worker/xbr/_marketmaker.py", line 1122, in start
  File ".tox/buildexe/lib/python3.7/site-packages/web3/contract.py", line 190, in __getattr__
web3.exceptions.MismatchedABI: ("The function 'marketsByMaker' was not found in this contract's abi. ", 'Are you sure you provided the correct contract abi?')

**Comment by oberstet** [comment]
> We don't know what wrong. Please, can you help us ?

CrossbarFX **v20.3.1** works with the corresponding XBR contracts **v20.3.1** (https://github.com/crossbario/xbr-protocol/tree/v20.3.1).

The error you see is likely due to the deployed contract versions not matching up.

Eg. the specific mapping not found `XBRNetwork.marketsByMaker` (https://github.com/crossbario/xbr-protocol/blob/3b81624ad5865c2ccde8029bacf46415dc0a82f3/contracts/XBRMarket.sol#L81) has been refactored on master to `XBRMarket.marketsByMaker` (https://github.com/crossbario/xbr-protocol/blob/f2811532894e9a34228228e280cd67fc5b1fc6c6/contracts/XBRMarket.sol#L80)

So when you deploy master branch of the contracts, the XBRNetwork contract might still be found by an older CrossbarFX (if the contract address hasn't changed), but it will fail when the (older) CrossbarFX is trying to access a mapping that was actually moved to a different contract on the ones deployed.

> Note: the repository and issue tracker here is for the XBR smart contracts only - _not_ CrossbarFX. Support for that is outside the scope of the XBR protocol (this repo) itself. The repo here is for issues relating to the XBR contract solidity code (https://github.com/crossbario/xbr-protocol/tree/master/contracts), not the CrossbarFX implementation of a XBR market maker.

**Comment by brunocoudoin** [comment]
Just added a test to make sure that marketsByMaker method is indeed deployed in the target blockchain. You have a [PR here for it](https://github.com/crossbario/xbr-protocol/pull/98).

I know it is not the right location to report this but just to let you know, when we run crossbarfx-linux-amd64-20200304-71305c5 or crossbarfx-linux-amd64-20200304-886d0bb we still have the reported error with the ABI Mismatch even when we target a ganache instance that passes the test in the PR.
